### ISSUE TITLE
Couldn't find index page for 'gurobipy' (maybe misspelled?)

### ISSUE THREAD

**Issue by xiekunwhy** [shahab-sarmashghi/RESPECT#16]
Hi,

I got following errors when installing RESPECP, do you know why and how to solve it?

mamba install -c conda-forge -c bioconda -c https://conda.anaconda.org/gurobi jellyfish seqtk gurobi
python setup.py install

Processing dependencies for respect==1.3.0
Searching for gurobipy>=7.0.2
Reading https://pypi.gurobi.com/gurobipy/
Couldn't find index page for 'gurobipy' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
error: The read operation timed out

Best,
Kun

**Comment by shahab-sarmashghi** [comment]
Hi Kun,

There were some issues with the newer versions of some dependencies so I changed the `setup.py` script to limit the `Python` version to `3.7` or `3.8`, and also some of the dependencies versions. I have also not tested installing using `mamba`. Can you create a new `conda` environment and install the latest release that I just published and only use `conda` to install dependencies to see if the issue is solved?
